### ISSUE TITLE
Run multiple instances of Octomap Server in ROS

### ISSUE THREAD

**Issue by boazMgm** [OctoMap/octomap_mapping#106]
Hi,
is there an option to run multiple instances of Octomap server in ROS?
for example, I want to build different occupancy grids with different sensors and compare between them.
Thanks!

**Comment by heheguoqushi** [comment]
Hi,I have tried to roslaunch two octomap servers. In the second server, I change all the topic name to be different from the first. Then make sure two octomap maps have been transformed in one map tf. Finally，I can see them in the rviz.
