### ISSUE TITLE
Facing this warning while running octomap server and nothing is beinig published on /occupied_cell_vis_array

### ISSUE THREAD

**Issue by Avi241** [OctoMap/octomap_mapping#113]
MessageFilter [target=world ]: Dropped 100.00% of messages so far. Please turn the [ros.octomap_server.message_filter] rosconsole logger to DEBUG for more information.

**Comment by jt7277** [comment]
Hi @Avi241, I'm having the same issue - could you please share your solution if you found one? Thanks
