### ISSUE TITLE
Warning : Nothing to publish, octree is empty

### ISSUE THREAD

**Issue by MallakAbunimeh** [OctoMap/octomap_mapping#115]
I am using cyglidar to get the 3D pointcloud to generate a 3D map in rviz using the octomap_server package. The following 2 images shows the cyglidar.launch file & the octomap_server.launch file  

Cyglidar launch file:
```
<launch>
  <!-- Arguments -->
  <arg name="version" default="2" doc="version type [0, 1, 2]"/> <!-- 0: 2D, 1: 3D, 2: Dual -->
  <arg name="frequency_level" default="0" doc="level [0 to 15]"/>
  <arg name="pulse_control" default="0" doc="pulse mode [0, 1]"/> <!-- 0: Auto, 1: Manual -->
  <arg name="pulse_duration" default="10000" doc="duration [0 to 10000]"/>

  <node pkg="cyglidar_d1" type="cyglidar_pcl_publisher" name="line_laser" output="screen">
    <param name="port" value="/dev/cyglidar"/>
    <param name="baud_rate" value="3000000"/>
    <param name="frame_id" value="laser_link"/>
    <param name="fixed_frame" value="/map"/>
    <param name="run_mode" value="1"/>
    <param name="frequency" value="$(arg frequency_level)"/>
    <param name="set_auto_duration" value="$(arg pulse_control)"/>
    <param name="duration" value="$(arg pulse_duration)"/>
  </node>

  <node pkg="rviz" type="rviz" name="rviz" args="-d $(find cyglidar_d1)/rviz/cyglidar_config.rviz"/>
  <node pkg="tf" type="static_transform_publisher" name="to_laserlink" args="0 0 0 0 0 0 1 map laser_link 10"/>
</launch>

```
octomap_server.launch file:
```
<!-- 
  Example launch file for octomap_server mapping: 
  Listens to incoming PointCloud2 data and incrementally builds an octomap. 
  The data is sent out in different representations. 

  Copy this file into your workspace and adjust as needed, see
  www.ros.org/wiki/octomap_server for details  
-->
<launch>
	<node pkg="octomap_server" type="octomap_server_node" name="octomap_server">
		<param name="resolution" value="0.022" />
		<!--param name="height_map" value="false" /-->

		<!-- fixed map frame (set to 'map' if SLAM or localization running!) -->
		<param name="frame_id" type="string" value="map" />
		
		<!-- maximum range to integrate (speedup!) -->
		<param name="sensor_model/max_range" value="-1" />

		<!-- minimum and mzximum height of points -->
		<param name="pointcloud_min_z" value="0.02" />
		<param name="pointcloud_maz_z" value="1.0" />
		
		<!-- data source to integrate (PointCloud2) -->
		<remap from="cloud_in" to="scan" />
	
	</node>
</launch>

```

After launching the cyglidar.launch file then the octomap_server.launch file I got this error. I also added the MarkerArray option in rviz and changed the topic to /occupied_cells_vis_array. Then, I got the following error:
[ WARN] [1675673929.993534530]: Nothing to publish, octree is empty.

I tried to verify the pointcloud is being published to scan topic but I get nothing back. I am using Ubuntu 20.0.4 and ros noetic version.

**Comment by wxmerkt** [comment]
Can you check the `rqt_graph` and potentially turn on DEBUG for the rosconsole (e.g. with `rqt_console`). It might be that messages are being ignored or topics arent connected

**Comment by MallakAbunimeh** [comment]
Hello, thanks for the reply. This is what the output was for `rqt_console`:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/114362747/217002401-dd75977a-0189-41ac-b3da-6a839c0c6213.png">
And this is the output for the `rqt_graph` with every parameter not hidden:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/114362747/217002914-4726af6c-55d2-4962-a409-b3cfc2863cfa.png">

**Comment by wxmerkt** [comment]
`rqt_graph` shows that your connections are not connected - `octomap_server` expects `scan` whereas your driver publishes `scan_3D`

**Comment by MallakAbunimeh** [comment]
@wxmerkt 

We changed the topic from scan to scan_3D in the octomap_mapping.launch file. However, we still get the same warning message and the topics published by the octomap_server are showing up as dead sinks. 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/114362747/217227296-e0e0f1a8-7a1a-4f11-ab50-269e5a93b0be.png">

The following image is also the topic list when the server is running:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/114362747/217227388-34ba3d68-94a1-42f7-9d3b-b25705be4b95.png">

We're not sure what exactly we're supposed to change to make sure the topics are connected.

**Comment by wxmerkt** [comment]
They are showing as dead sinks since no node is subscribed to them - and that includes RViz. Please try to activate the DEBUG output in the console settings to see more detail on why messages may have been ignored. Also make sure the frames / transforms required you are mapping in are correct and available

**Comment by MallakAbunimeh** [comment]
I tried to launch the cyglidar.launch file again and then the octomap_mapping.launch file with RVIZ instead of launching it in the cyglidar package and then got this error:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/114362747/218297008-b4cf34b0-91de-4eda-9454-ee754b314793.png">

<img width="841" alt="image" src="https://user-images.githubusercontent.com/114362747/218297049-d78a73b5-1afd-4d39-b186-1e320c2617ab.png">

After activating the DEBUG output in rqt_console I got this:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/114362747/218297072-632568b7-5771-45c8-a347-609a28ab4d44.png">

And here are the connections on rqt graph:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/114362747/218297115-a6efe26f-edec-4ac7-a523-4d058d78d46f.png">

**Comment by MallakAbunimeh** [comment]
I tried to run the octomap_mapping launch file again and got this error:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/114362747/218305080-2905939d-c169-45b7-a6e5-b65812270f3b.png">

Here is the rqt graph output:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/114362747/218305124-6221d4ae-c3f9-4106-bc29-434bfdc09c37.png">

The DEBUG output:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/114362747/218305209-39f3b9d1-e8f8-41e7-a3ba-25f3c23014cb.png">

<img width="957" alt="image" src="https://user-images.githubusercontent.com/114362747/218305237-ea0dfe84-3b0f-4e87-8b1c-d7fc519cd4ab.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/114362747/218305252-93c50d39-5022-4edd-818b-ec7678eaf69d.png">

**Comment by wxmerkt** [comment]
Do the transforms from `map` to your lidar frame exist?

**Comment by MallakAbunimeh** [comment]
It only shows when I launch rviz in cyglidar.launch file:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/114362747/218879893-b7d2feed-5477-45b9-80c5-4abaf56d24ad.png">

**Comment by wxmerkt** [comment]
Are they connected? cf. rqt_tf_tree or echo the transform

**Comment by MallakAbunimeh** [comment]
This is what I got:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/114362747/219254109-82d4e591-873d-4905-8290-3ab5fa507292.png">

Note: . This only appears when I launch RVIZ in the cyglidar.launch file; however, after commenting the RVIZ launching node in the cyglidar.launch file, I was unable to open RVIZ in the octomap_mapping.launch file. So, can you also check line 27 for me please? I want to know why RVIZ is not opening in the octomap_mapping.launch file. Is this line correctly written? Or I need to rewrite it or do something to make it launch? Because I want to get the 3D map in the octomap_mapping launch file.

Line 27 in octomap_mapping launch file is shown below:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/114362747/219257019-8949038d-bc53-41c5-804c-4aff960c4739.png">

**Comment by MallakAbunimeh** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/114362747/219302024-f75a514b-d2aa-4d4a-805d-9d8b0a7e1c73.png">
