### ISSUE TITLE
Octomap server node crashes in ROS 2 Rolling

### ISSUE THREAD

**Issue by hello-chintan** [OctoMap/octomap_mapping#119]
Hello,

I am working with the ROS 2 Rolling binaries of Octomap and every time I try to launch octomap server node, the process dies without any errors. With the same launch file, I am able to get Octomap to work stably in ROS 2 Humble. Has Octomap been tested in Rolling?

I would welcome all help and suggestions. Please let me know if you need additional information.

Thank you,
Chintan

**Comment by wxmerkt** [comment]
@wep21 do you have any insights here?
