### ISSUE TITLE
Release octomap_server in jade

### ISSUE THREAD

**Issue by mmurooka** [OctoMap/octomap_mapping#24]
Cloud you release deb package of octomap_server in jade?
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1276#issuecomment-152463121

**Comment by ahornung** [comment]
Release is on its way towards to build farm.

**Comment by mmurooka** [comment]
Thank you.

**Comment by ahornung** [comment]
octomap_mapping arrived in the shadow-fixed repo, will appear in public at the next sync: http://www.ros.org/debbuild/jade

Closing here.

**Comment by mmurooka** [comment]
Thank you!
