### ISSUE TITLE
Is ROS Kinetic supported yet?

### ISSUE THREAD

**Issue by sytelus** [OctoMap/octomap_mapping#30]
I don't see octomap_mapping or octomap_server packages in ros-kinetic. Is Kinetic supported yet? These are the only packages that is preventing us to move on to Kinetic :(. It's especially bad because if we want to downgrade to Jade then we also have to downgrade OS to Ubuntu 14.04 because Ubuntu 15 support expires in few month. 

Is there anyway to use mapping and server packages on Kinetic?

Thanks!

**Comment by ahornung** [comment]
I currently lack the time to test octomap_server in Kinetic. If there is support from the community by testing the compilation and basic functionlity of octomap_server in Kinetic, then this would drastically speed up a release

Basically, the state of `kinetic-devel` (I just created a new branch based on `jade-devel` should just work.

**Comment by sytelus** [comment]
May be we can just start with that? If you can publish these packages in Kinetic release then we can start using them and file bugs as we encounter.

**Comment by ahornung** [comment]
A broken package can delay the complete build farm. Only tested and working packages should be released, otherwise users will stumble over non-working code.

But on the other hand there's no need to have a binary release for testing and bug fixing. Why not add octomap_mapping to your catkin source checkout and compile?

**Comment by LorenzMeier** [comment]
Never mind - the install instructions for the ROS kinect driver have the side-effect of installing a different, non-compatible GCC version. Will report back in a sec.

**Comment by james-ward** [comment]
I have built and deployed the kinetic-devel branch on ROS kinetic. It builds and runs fine.

**Comment by KvalheimRacing** [comment]
How did you do it?

**Comment by james-ward** [comment]
@KvalheimRacing It's a pretty standard catkin build.
Make a workspace ( http://wiki.ros.org/catkin/Tutorials/create_a_workspace ), then clone the source into it:

```
source /opt/ros/kinetic/setup.bash
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src
catkin_init_workspace
git clone -b kinetic-devel https://github.com/OctoMap/octomap_mapping.git
cd ~/catkin_ws
catkin_make
catkin_make install
```

**Comment by KvalheimRacing** [comment]
Ah ofc, thanks!

**Comment by KvalheimRacing** [comment]
Is there any prefered target link library? In my CMakeLists.txt file, I dont know how to make a library/"MY_TARGET_NAME". Or, I know that the library not should be made in the CMakeList.txt file, but I dont know where.

edit: I just typed; link_libraries(${OCTOMAP_LIBRARIES}), and got to install all. But now there are errors from all the place when I run the `roslaunch octomap_mapping.launch octomap_mapping_nodelet.launch`
starting with; 
ERROR: cannot launch node of type [octomap_server/octomap_server_node]: octomap_server

**Comment by ahornung** [comment]
> I have built and deployed the kinetic-devel branch on ROS kinetic. It builds and runs fine.

Thanks! A release for kinetic (0.6.1) is on the way to the build farm.

**Comment by james-ward** [comment]
The package appeared on the repo yesterday.
Just installed it - works nicely.

**Comment by saurabhbansal90** [comment]
Hello Guys, I am planning to use Octomap for my robot arm manipulation, for obstacle avoidance.
So for that purpose, I think  I will be following steps below:
1. Get the point cloud from sensor
2. Run a Octomap server node to receive the point cloud
3. From Octomap server, subscribe to the binary octomap

Then how to pass this binary data to some path planner for obstacle avoidance.

Can somebody please confirm, if I have to use this approach only.
And if there is some example implementation  that I can make use of.

With best regards,
Saurabh

**Comment by ahornung** [comment]
Hello Saurabh,

your best bet would be to look at the MoveIt! package. It incorporates 
all the steps + manipulation planning.

**Comment by saurabhbansal90** [comment]
Hello Armin, thanks for your response.
Yes its available in MoveIt package only. I folllowed this [link](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/perception_configuration.html).

It is working fine apart from showing a TF error. I am resolving that error.
