### ISSUE TITLE
Help with launch file

### ISSUE THREAD

**Issue by akshayshetty** [OctoMap/octomap_mapping#32]
Hi all,

I think I am having some problem with the remapping as nothing is being published to the /occupied_cells_vis_array. I have my pointcloud2 being published to /velodyne_cloud_registered. The frame id of this message is /sensor_init_rot.

In the launch file for octomap_server, I have tried using different values for frame_id: odom_combined, map, sensor_init_rot. This is how it currently looks:

```
<launch>
    <node pkg="octomap_server" type="octomap_server_node" name="octomap_server">
        <param name="resolution" value="0.05" />

        <!-- fixed map frame (set to 'map' if SLAM or localization running!) -->
        <param name="frame_id" type="string" value="odom_combined" />

        <!-- maximum range to integrate (speedup!) -->
        <param name="sensor_model/max_range" value="100.0" />

        <!-- data source to integrate (PointCloud2) -->
        <remap from="cloud_in" to="/velodyne_cloud_registered" />

    </node>
</launch>
```

I can launch octomap_mapping.launch without any errors or warning. However, nothing is being published to /occupied_cells_vis_array.

Any help would be appreciated. Thanks!

**Comment by ahornung** [comment]
This can have a number of different reasons, the most common one being that your TF tree is not working correctly. Best debug with rqt_console.

ROS answers is probably the best place for these kinds of questions.
