### ISSUE TITLE
Release for ROS Melodic Morenia

### ISSUE THREAD

**Issue by mjbogusz** [OctoMap/octomap_mapping#49]
Will `octomap_server` (and `octomap_ros`) be released (packaged and available in repo) for ROS Melodic?

I've tested the `melodic-devel` branch by adding the packages to a catkin workspace and it worked flawlessly as far as our usecase goes (Gazebo simulation, Kinect for mapping and planning robot motion based on current octomap state).

**Comment by ahornung** [comment]
I'm not planning any more releases of octomap_server at the moment, since I can't maintain it myself anymore. Even if working "as-is", there are bound to be patches and fixes necessary at some point in time. So I think it's best to add it to a source workspace and build manually.

I added another release of octomap_ros though, even if it doesn't look like there are any packages directly depending on it.

**Comment by wxmerkt** [comment]
@ahornung I am happy to volunteer to do the release for melodic and look at pull requests and fixes that may come in, time permitting. There are some upstream dependent packages which would be a great benefit to the community if we could get them released/unblocked (e.g., `jsk_rviz_plugins`).

**Comment by ahornung** [comment]
Sounds good to me, thanks for volunteering!

@mikaelarguedas @dirk-thomas @wjwwood could you add @wxmerkt  as maintainer to ros-gbp/octomap_mapping-release?

**Comment by dirk-thomas** [comment]
> could you add @wxmerkt as maintainer to ros-gbp/octomap_mapping-release?

Done.

**Comment by wxmerkt** [comment]
Thank you very muich @ahornung and @dirk-thomas! I am happy to make the release. Are there any outstanding pull requests or features we'd like to get in before releasing? Otherwise I'll release `0.6.1` as on kinetic to melodic.

**Comment by wxmerkt** [comment]
I have released `0.6.1` to melodic from `kinetic-devel`: https://github.com/ros/rosdistro/pull/19985 as there are no changes yet in `melodic-devel`.

**Comment by ahornung** [comment]
@wxmerkt I'm getting a few "Build failed" messages from the build farm, could you look into it? It might be best to switch out my email address for yours as maintainer.

**Comment by wxmerkt** [comment]
I am happy to look into it. Could you please give me write access to this repo as well?

**Comment by ahornung** [comment]
Done, added you to all the ROS repos `octomap_*`.
One of the failing jobs is here: http://build.ros.org/job/Mbin_ubv8_uBv8__octomap_server__ubuntu_bionic_arm64__binary/3/display/redirect

They all appear to be ARM jobs, so maybe they just need to be blacklisted for the platform.

**Comment by wxmerkt** [comment]
Thank you! I’ll have a look into it and will update the maintainer email.

**Comment by wxmerkt** [comment]
`octomap_mapping` has now been released to `melodic`. It will be available after the next melodic sync.

**Comment by iscsrl** [comment]
Hi, any update about the release for Ros Melodic?

**Comment by wxmerkt** [comment]
This package has been released and is available on ROS Melodic: `ros-melodic-octomap-mapping`. Please let me know if you have any issues
