### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cedrusx** [OctoMap/octomap_mapping#57]
Dear contributors, would you consider to specify a license for this project? Thanks!

From [GitHub Help](https://help.github.com/en/articles/licensing-a-repository):
> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by wxmerkt** [comment]
The package files specify the BSD license:

https://github.com/OctoMap/octomap_mapping/blob/d126754ba1ea13167c452dbc360585e9c61dbd03/octomap_mapping/package.xml#L9

https://github.com/OctoMap/octomap_mapping/blob/d126754ba1ea13167c452dbc360585e9c61dbd03/octomap_server/package.xml#L9
