### ISSUE TITLE
problem in filtering pointcloud

### ISSUE THREAD

**Issue by icesit** [OctoMap/octomap_mapping#58]
Hello.
In OctomapServer.cpp, line 318 to 323, the pass_x, pass_y and pass_z has filtered the point cloud. However, later in line 334 to 339, the filter worked again.
I think maybe this is a bug? Should the filter action only be done in base frame but not in world frame?

**Comment by wxmerkt** [comment]
This is surrounded by an if-statement and the filter is in repeated for each of the branches. As thus, it is not done twice.
