### ISSUE TITLE
Can OctoMap unoccupy? 

### ISSUE THREAD

**Issue by bomarali** [OctoMap/octomap_mapping#62]
Does OctoMap work with dynamic objects at all? Say if I want to grasp an object and move it, will the OctoMap reflect the change? So far I have been playing with sensor model but I cannot seem to make the OctoMap forget the original position of the object.

**Comment by ahornung** [comment]
There is no explicit decay or labeling of dynamic objects. For an object to clear, you need to see a sufficient number of points in the background behind the removed object, or modify the code to use "maxrange" readings for clearing only. A tweaked sensor model helps to clear an object faster.

**Comment by bomarali** [comment]
My bad, I transformed the point cloud to a different frame before feeding into the octomap server.

**Comment by murikill** [comment]
I'm still having the same issue - dynamically objects won't removed. I think, there are enough points in the background, but the cells doesn't disappear. What do I wrong? 
Thank you!
![octomap](https://user-images.githubusercontent.com/16001211/124927313-c84b5700-dffe-11eb-8b6b-c6d556dc2bed.png)

**Comment by jarvisyjw** [comment]
> I'm still having the same issue - dynamically objects won't removed. I think, there are enough points in the background, but the cells doesn't disappear. What do I wrong? Thank you! ![octomap](https://user-images.githubusercontent.com/16001211/124927313-c84b5700-dffe-11eb-8b6b-c6d556dc2bed.png)

Have you solved it? I am facing the same thing.
