### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Jrdevil-Wang** [OctoMap/octomap_mapping#71]
Hello, I am doing some experiments using octomap, and something strange occur on performance.

When I use the default octomap version along with ROS melodic (Ubuntu 18.04), I get the debug log like this:

> Pointcloud insertion in OctomapServer done (0+307200 pts (ground/nonground), 0.564149 sec)

But when I use the version compiled with github kinetic-devel, it is much slower and I get the debug log like this:

> Pointcloud insertion in OctomapServer done (0+307200 pts (ground/nonground), 6.756059 sec)

Any idea what would cause this difference? Many thanks!

**Comment by wxmerkt** [comment]
How did you compile/what are your workspace settings? Is Release mode set?

**Comment by Jrdevil-Wang** [comment]
Thank you for your quick reply!
It was my mistake that I forget to set release mode. Did not realize that there could be that much difference.
I recompiled the workspace with "catkin_make -DCMAKE_BUILD_TYPE=Release", and the performance looks fine.
Let me close this issue and sorry for your trouble.
