### ISSUE TITLE
Noise accumulated with 2D map

### ISSUE THREAD

**Issue by JasDEng** [OctoMap/octomap_mapping#74]
Hello, I am currently using octomap ros pkg to generate a 2d projected map.

I was able to see my 2d map with rviz. For y-axis, if y >0, it keeps building noise point cloud into the map and doesn't clear it or update at all, while it is not the case if y < 0.

![3](https://user-images.githubusercontent.com/58424655/87773252-7772a980-c855-11ea-8f50-7f05aaa71c30.jpg)

Could someone help please. I really appreciate it.

**Comment by jarvisyjw** [comment]
Hi, How did you solved it? I am facing the same issue.
