### ISSUE TITLE
how to convert the coloroctree to octree

### ISSUE THREAD

**Issue by chengm0-0** [OctoMap/octomap_mapping#80]
Hi, when I use the fcl library, I want to convert the coloroctree to octree, but I do not find any method. I have tried the following way, but it did not make any difference.
octomap::ColorOcTree* octree = new octomap::ColorOcTree(0.1);
octomap::OcTree* octree1 = dynamic_castoctomap::OcTree*(octree);
Could you help me solve this question?
Thanks! :)

**Comment by ahornung** [comment]
Duplicate: https://github.com/OctoMap/octomap/issues/315
