### ISSUE TITLE
/reset service does not work

### ISSUE THREAD

**Issue by saharLeisiazar** [OctoMap/octomap_mapping#85]
Hi
I am using octomap_server on  ros Melodic and in my project I need to reset the /projected_map while mapping. But the /reset service does not work. I remember I had Kinetic before and did not have this problem but now that I am using Melodic, this service is not working. Is there any other way I can reset my map?

**Comment by wxmerkt** [comment]
HI @saharLeisiazar,
Can you describe what happens when you call the reset service? Is there a response? The relevant code did not change between the released version for Kinetic (0.6.4) and the one released for Melodic (0.6.5) - cf. https://github.com/OctoMap/octomap_mapping/compare/0.6.4...0.6.5

**Comment by saharLeisiazar** [comment]
Thanks for responding @wxmerkt
Nothing happens. no response, no error
![Screenshot from 2021-03-23 08-05-40](https://user-images.githubusercontent.com/49044284/112230480-1e33f480-8bf2-11eb-82ba-9ee4efa4a198.png)

**Comment by ValentinaMiller** [comment]
+1

**Comment by wxmerkt** [comment]
@saharLeisiazar @ValentinaMiller can you please try #92 and let me know if that fixes your issues?
