### ISSUE TITLE
when OccupancyMap in Rviz, corrupted size vs. prev_size in fastbins and core dumped 

### ISSUE THREAD

**Issue by muratkoc503** [OctoMap/octomap_mapping#96]
Hi,
Firtly, i constructed octomap as .bt file. Then, i load .bt map file with octomap_server_node. This is Ok. 
then, i start rviz. After, i add OcuppancyMap which come from rviz plugin. After i select Octomap Binary Topic as /octomap_binary. when i do this, rviz closed and this message observed in terminal:

> corrupted size vs. prev_size in fastbins
Aborted (core dumped)

How i visualise octomap .bt file in Rviz?
Thanks.

**Comment by wxmerkt** [comment]
Hi @muratkoc503
Could you provide the `.bt` file to help reproduce the failure? A good way to reproduce would be to build rviz and octomap_rviz_plugins with Debug symbols and then run rviz with `gdb`. This allows you to figure out where things go wrong

**Comment by muratkoc503** [comment]
@wxmerkt Thanks for answer. I reproduce .bt file. This is solved problem. Previously, i construct map and after i install rviz plugin. Maybe, this may cause my problem
